---
# License: MIT

# Author Information
# Larry Smith Jr.
# http://everythingshouldbevirtual.com
# https://www.twitter.com/mrlesmithjr
# mrlesmithjr@gmail.com

# To view available options and settings reference the environment.yml in
# Test/dummy/server/environment.yml
provisioners: []
synced_folders: []
nodes:
  - name: node0
    ansible_groups:
      - test_nodes
    box: mrlesmithjr/freenas112
    desktop: false
    disable_synced_folders: true
    disks: []
    interfaces: []
    linked_clone: true
    manage_hostname: false
    mem: 2048
    provision: false
    provisioners: []
    vcpu: 1
    port_forwards:
      - guest: 80
        host: 8080
    windows: false
