---
# Global provisioners
# Will run against every node
# For node specific provisioners add at the node level
provisioners: []


# Synced folders
# Additional synced folders. By default scripts and playbooks are synced
synced_folders: []


# Define nodes
nodes:
  - name: node0
    ansible_groups:
      - test_nodes
    box: mrlesmithjr/alpine37
    desktop: false
    disks: []
    interfaces:
      - ip: 192.168.250.10
        auto_config: true
        method: static
    linked_clone: true
    mem: 512
    provision: false
    provisioners: []
    synced_folder:
      type: nfs
    vcpu: 1
    port_forwards: []
    windows: false

