---
# Global provisioners
# Will run against every node
# For node specific provisioners add at the node level
provisioners: []


# Synced folders
# Additional synced folders. By default scripts and playbooks are synced
synced_folders: []


# Define nodes
nodes:
  - name: node0
    ansible_groups:
      - test_nodes
    box: mrlesmithjr/windows2016
    desktop: false
    disks: []
    interfaces: []
    linked_clone: true
    mem: 2048
    provision: false
    provisioners: []
    vcpu: 1
    port_forwards: []
    windows: true

